//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.MessageWorkerService.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.MessageWorkerService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Refund appeal accepted, check details 的本地化字符串。
        /// </summary>
        public static string BackOfficeRefundOrderSubTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund appeal-{0} 的本地化字符串。
        /// </summary>
        public static string BackOfficeRefundOrderTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have got one pay bill message, check details 的本地化字符串。
        /// </summary>
        public static string BillerCompleteSubTitle {
            get {
                return ResourceManager.GetString("BillerCompleteSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have failed to make one pay bill, check details 的本地化字符串。
        /// </summary>
        public static string BillerFailSubTitle {
            get {
                return ResourceManager.GetString("BillerFailSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay Bill Failed - {0} 的本地化字符串。
        /// </summary>
        public static string BillerFailTitle {
            get {
                return ResourceManager.GetString("BillerFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay Bill-{0} 的本地化字符串。
        /// </summary>
        public static string BillerTitle {
            get {
                return ResourceManager.GetString("BillerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have got one payment message, check details 的本地化字符串。
        /// </summary>
        public static string ConsumeSubTitle {
            get {
                return ResourceManager.GetString("ConsumeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense-{0} 的本地化字符串。
        /// </summary>
        public static string ConsumeTitle {
            get {
                return ResourceManager.GetString("ConsumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} deposited failed, check details 的本地化字符串。
        /// </summary>
        public static string DepositCancelSubTitle {
            get {
                return ResourceManager.GetString("DepositCancelSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit-{0} 的本地化字符串。
        /// </summary>
        public static string DepositCancelTitle {
            get {
                return ResourceManager.GetString("DepositCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one deposit completed, check details 的本地化字符串。
        /// </summary>
        public static string DepositSubTitle {
            get {
                return ResourceManager.GetString("DepositSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposited-{0} 的本地化字符串。
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid QR code, please scan again 的本地化字符串。
        /// </summary>
        public static string EMGatewayOrderNotExist {
            get {
                return ResourceManager.GetString("EMGatewayOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your application has passed the review，check details 的本地化字符串。
        /// </summary>
        public static string FiiipayMerchantCertifiedSubTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantCertifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Review - Pass 的本地化字符串。
        /// </summary>
        public static string FiiipayMerchantCertifiedTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantCertifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your application has failed to pass the review , check details 的本地化字符串。
        /// </summary>
        public static string FiiipayMerchantDisapprovalSubTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantDisapprovalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Review - Fail 的本地化字符串。
        /// </summary>
        public static string FiiipayMerchantDisapprovalTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantDisapprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your refund request has finished, check details 的本地化字符串。
        /// </summary>
        public static string GatewayOrderPaymentRefundSubTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentRefundSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund-{0} 的本地化字符串。
        /// </summary>
        public static string GatewayOrderPaymentRefundTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentRefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have an online payment order, check details 的本地化字符串。
        /// </summary>
        public static string GatewayOrderPaymentSubTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Payment-{0} 的本地化字符串。
        /// </summary>
        public static string GatewayOrderPaymentTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This FiiiPOS has accepted your invitation, the merchant name is {0} 的本地化字符串。
        /// </summary>
        public static string InviteFiiiposSuccessSubTitle {
            get {
                return ResourceManager.GetString("InviteFiiiposSuccessSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward-Invite FiiiPOS to Register 的本地化字符串。
        /// </summary>
        public static string InviteFiiiposSuccessTitle {
            get {
                return ResourceManager.GetString("InviteFiiiposSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Failed 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Passed 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Residential proof was verified failed, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Failed 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Residential proof has been approved, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Passed 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one order was refund, check details 的本地化字符串。
        /// </summary>
        public static string RefundSubTitle {
            get {
                return ResourceManager.GetString("RefundSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund-{0} 的本地化字符串。
        /// </summary>
        public static string RefundTitle {
            get {
                return ResourceManager.GetString("RefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FiiiPOS from your account, the merchant name is {0} 的本地化字符串。
        /// </summary>
        public static string RewardUnbindFiiiposSubTitle {
            get {
                return ResourceManager.GetString("RewardUnbindFiiiposSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward-Unbind FiiiPOS from Your Account 的本地化字符串。
        /// </summary>
        public static string RewardUnbindFiiiposTitle {
            get {
                return ResourceManager.GetString("RewardUnbindFiiiposTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have made a payment, see details 的本地化字符串。
        /// </summary>
        public static string StoreOrderConsumeSubTitle {
            get {
                return ResourceManager.GetString("StoreOrderConsumeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline payment-{0} 的本地化字符串。
        /// </summary>
        public static string StoreOrderConsumeTitle {
            get {
                return ResourceManager.GetString("StoreOrderConsumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have received a payment, see detail 的本地化字符串。
        /// </summary>
        public static string StoreOrderIncomeSubTitle {
            get {
                return ResourceManager.GetString("StoreOrderIncomeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Received-{0} 的本地化字符串。
        /// </summary>
        public static string StoreOrderIncomeTitle {
            get {
                return ResourceManager.GetString("StoreOrderIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have received one transfer from FiiiExchange, check details 的本地化字符串。
        /// </summary>
        public static string TransferFromFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(in)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferFromFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have received one transfer from {0}, check details 的本地化字符串。
        /// </summary>
        public static string TransferIntoSubTitle {
            get {
                return ResourceManager.GetString("TransferIntoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(in)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferIntoTitle {
            get {
                return ResourceManager.GetString("TransferIntoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one transfer completed, check details 的本地化字符串。
        /// </summary>
        public static string TransferOutSubTitle {
            get {
                return ResourceManager.GetString("TransferOutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(out)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferOutTitle {
            get {
                return ResourceManager.GetString("TransferOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one transfer to FiiiExchange completed, check details 的本地化字符串。
        /// </summary>
        public static string TransferToFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(out)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferToFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal was failed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal completed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient balance. 的本地化字符串。
        /// </summary>
        public static string 余额不足 {
            get {
                return ResourceManager.GetString("余额不足", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonus-FIII 的本地化字符串。
        /// </summary>
        public static string 奖励FIII {
            get {
                return ResourceManager.GetString("奖励FIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonus of FiiiCoin has been arrived your account, check details 的本地化字符串。
        /// </summary>
        public static string 奖励子标题 {
            get {
                return ResourceManager.GetString("奖励子标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order is paied or refunded, please do not pay again 的本地化字符串。
        /// </summary>
        public static string 订单已完成或者已退款 {
            get {
                return ResourceManager.GetString("订单已完成或者已退款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order to be paid 的本地化字符串。
        /// </summary>
        public static string 订单待支付通知 {
            get {
                return ResourceManager.GetString("订单待支付通知", resourceCulture);
            }
        }
    }
}
