//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPOS.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPOS.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been bound to other POS 的本地化字符串。
        /// </summary>
        public static string AccountHasBoundOtherPOS {
            get {
                return ResourceManager.GetString("AccountHasBoundOtherPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please login as account was bound to the FiiiPOS 的本地化字符串。
        /// </summary>
        public static string AccountHasBoundThisPOS {
            get {
                return ResourceManager.GetString("AccountHasBoundThisPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant account not found 的本地化字符串。
        /// </summary>
        public static string AccountNotExists {
            get {
                return ResourceManager.GetString("AccountNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been unbound 的本地化字符串。
        /// </summary>
        public static string AccountUnbundled {
            get {
                return ResourceManager.GetString("AccountUnbundled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cryptocurrency cannot be used currently, please contact customer service if any question 的本地化字符串。
        /// </summary>
        public static string CurrencyForbidden {
            get {
                return ResourceManager.GetString("CurrencyForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid tag 的本地化字符串。
        /// </summary>
        public static string EMInvalidTag {
            get {
                return ResourceManager.GetString("EMInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to generate address 的本地化字符串。
        /// </summary>
        public static string FailedGenerateAddress {
            get {
                return ResourceManager.GetString("FailedGenerateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot withdraw between FiiiPOS users 的本地化字符串。
        /// </summary>
        public static string FiiiPOSCantWithdrawToFiiiPOS {
            get {
                return ResourceManager.GetString("FiiiPOSCantWithdrawToFiiiPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity Verify Passed 的本地化字符串。
        /// </summary>
        public static string Merchant_KYC_LV1_DefaultBody {
            get {
                return ResourceManager.GetString("Merchant_KYC_LV1_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license Verify Passed 的本地化字符串。
        /// </summary>
        public static string Merchant_KYC_LV2_DefaultBody {
            get {
                return ResourceManager.GetString("Merchant_KYC_LV2_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Failed 的本地化字符串。
        /// </summary>
        public static string MerchantLv1Reject {
            get {
                return ResourceManager.GetString("MerchantLv1Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv1RejectSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv1RejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Passed 的本地化字符串。
        /// </summary>
        public static string MerchantLv1Verified {
            get {
                return ResourceManager.GetString("MerchantLv1Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv1VerifiedSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv1VerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Failed 的本地化字符串。
        /// </summary>
        public static string MerchantLv2Reject {
            get {
                return ResourceManager.GetString("MerchantLv2Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license was verified failed, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv2RejectSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv2RejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Passed 的本地化字符串。
        /// </summary>
        public static string MerchantLv2Verified {
            get {
                return ResourceManager.GetString("MerchantLv2Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license has been approved, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv2VerifiedSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv2VerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html,
        ///        body {
        ///            box-sizing: border-box;
        ///            margin: 0;
        ///            padding: 0;
        ///            min-width: 320px;
        ///            font-family: &quot;PingFang SC&quot;;
        ///            font-size: 100%;
        ///            color: #606266;
        ///            font-weight: 600;
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string NewsTemplate {
            get {
                return ResourceManager.GetString("NewsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account does not bind to this POS machine 的本地化字符串。
        /// </summary>
        public static string NoBindRelationship {
            get {
                return ResourceManager.GetString("NoBindRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PIN format 的本地化字符串。
        /// </summary>
        public static string PIN格式不正确 {
            get {
                return ResourceManager.GetString("PIN格式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POS has been bound to other Account 的本地化字符串。
        /// </summary>
        public static string POSHasBoundOtherAccount {
            get {
                return ResourceManager.GetString("POSHasBoundOtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have got one payment message, check details 的本地化字符串。
        /// </summary>
        public static string ReceiptSubTitle {
            get {
                return ResourceManager.GetString("ReceiptSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recieved payment-{0} 的本地化字符串。
        /// </summary>
        public static string ReceiptTitle {
            get {
                return ResourceManager.GetString("ReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid SN, please contact customer service 的本地化字符串。
        /// </summary>
        public static string SN码不存在 {
            get {
                return ResourceManager.GetString("SN码不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant information Verify Passed 的本地化字符串。
        /// </summary>
        public static string Store_DefaultBody {
            get {
                return ResourceManager.GetString("Store_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant information Verify Failed 的本地化字符串。
        /// </summary>
        public static string StoreReject {
            get {
                return ResourceManager.GetString("StoreReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant information Verify Passed 的本地化字符串。
        /// </summary>
        public static string StoreVerified {
            get {
                return ResourceManager.GetString("StoreVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant information verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string StoreVerifiedSubTitle {
            get {
                return ResourceManager.GetString("StoreVerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant information verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string StroeRejectSubTitle {
            get {
                return ResourceManager.GetString("StroeRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token expired. 的本地化字符串。
        /// </summary>
        public static string Token已失效 {
            get {
                return ResourceManager.GetString("Token已失效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have succesfully withdraw {0} of {1} 的本地化字符串。
        /// </summary>
        public static string WithdrawalEmailContent {
            get {
                return ResourceManager.GetString("WithdrawalEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdrawal of {0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalEmailTitle {
            get {
                return ResourceManager.GetString("WithdrawalEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have failed to withdraw {0} of {1}, please contact customer service 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectEmailContent {
            get {
                return ResourceManager.GetString("WithdrawalRejectEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdrawal of {0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectEmailTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal was failed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal completed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload failed. 的本地化字符串。
        /// </summary>
        public static string 上传失败 {
            get {
                return ResourceManager.GetString("上传失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupport cryptocurrency 的本地化字符串。
        /// </summary>
        public static string 不支持的币种 {
            get {
                return ResourceManager.GetString("不支持的币种", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot less than the minimal withdrawal amount 的本地化字符串。
        /// </summary>
        public static string 不能低于最低提币量 {
            get {
                return ResourceManager.GetString("不能低于最低提币量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot higher than the maxinum withdrawal amount 的本地化字符串。
        /// </summary>
        public static string 不能高于单次提币量 {
            get {
                return ResourceManager.GetString("不能高于单次提币量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reach the withdrawal limit today 的本地化字符串。
        /// </summary>
        public static string 今日提币达到限额 {
            get {
                return ResourceManager.GetString("今日提币达到限额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance not enough. 的本地化字符串。
        /// </summary>
        public static string 余额不足 {
            get {
                return ResourceManager.GetString("余额不足", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total amount must be greater than zero 的本地化字符串。
        /// </summary>
        public static string 到账数量不能为零或者负数 {
            get {
                return ResourceManager.GetString("到账数量不能为零或者负数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect original email addreess 的本地化字符串。
        /// </summary>
        public static string 原邮箱地址不正确 {
            get {
                return ResourceManager.GetString("原邮箱地址不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent successfully. 的本地化字符串。
        /// </summary>
        public static string 发送成功 {
            get {
                return ResourceManager.GetString("发送成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can check your own order only 的本地化字符串。
        /// </summary>
        public static string 只能查看自己的订单 {
            get {
                return ResourceManager.GetString("只能查看自己的订单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant account not support this cryptocurrency. 的本地化字符串。
        /// </summary>
        public static string 商户不支持的币种 {
            get {
                return ResourceManager.GetString("商户不支持的币种", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The country not exist. 的本地化字符串。
        /// </summary>
        public static string 国家不存在 {
            get {
                return ResourceManager.GetString("国家不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not verify Google authenticator 的本地化字符串。
        /// </summary>
        public static string 尚未绑定谷歌验证 {
            get {
                return ResourceManager.GetString("尚未绑定谷歌验证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant ID already exists, please enter again 的本地化字符串。
        /// </summary>
        public static string 帐号已存在 {
            get {
                return ResourceManager.GetString("帐号已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has locked. 的本地化字符串。
        /// </summary>
        public static string 帐号已锁定 {
            get {
                return ResourceManager.GetString("帐号已锁定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone number and account do not match  的本地化字符串。
        /// </summary>
        public static string 当前手机号与账号绑定的手机号不一致 {
            get {
                return ResourceManager.GetString("当前手机号与账号绑定的手机号不一致", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid withdrawal address 的本地化字符串。
        /// </summary>
        public static string 提币地址不是有效的地址 {
            get {
                return ResourceManager.GetString("提币地址不是有效的地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order exception, rejected by systerm, please contact customer service 的本地化字符串。
        /// </summary>
        public static string 提币失败备注 {
            get {
                return ResourceManager.GetString("提币失败备注", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new PIN can&apos;t be the same as the original PIN 的本地化字符串。
        /// </summary>
        public static string 新PIN不能与原PIN一样 {
            get {
                return ResourceManager.GetString("新PIN不能与原PIN一样", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New phone number should be different from the old one 的本地化字符串。
        /// </summary>
        public static string 新手机号码不能与原来的一致 {
            get {
                return ResourceManager.GetString("新手机号码不能与原来的一致", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New email address should be different from the old one 的本地化字符串。
        /// </summary>
        public static string 新邮箱不能和原来的邮箱一致 {
            get {
                return ResourceManager.GetString("新邮箱不能和原来的邮箱一致", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid payment code. 的本地化字符串。
        /// </summary>
        public static string 无效的用户Token {
            get {
                return ResourceManager.GetString("无效的用户Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdrawal amount reach the limit of this month 的本地化字符串。
        /// </summary>
        public static string 本月提币达到限额 {
            get {
                return ResourceManager.GetString("本月提币达到限额", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid format. 的本地化字符串。
        /// </summary>
        public static string 格式不正确 {
            get {
                return ResourceManager.GetString("格式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email account already exit on FiiiPos, please try with new one 的本地化字符串。
        /// </summary>
        public static string 此邮箱已经绑定到其他邮箱 {
            get {
                return ResourceManager.GetString("此邮箱已经绑定到其他邮箱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account not found. 的本地化字符串。
        /// </summary>
        public static string 用户不存在 {
            get {
                return ResourceManager.GetString("用户不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User account not support this cryptocurrency. 的本地化字符串。
        /// </summary>
        public static string 用户不支持的币种 {
            get {
                return ResourceManager.GetString("用户不支持的币种", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw forbidden 的本地化字符串。
        /// </summary>
        public static string 禁止提币 {
            get {
                return ResourceManager.GetString("禁止提币", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment forbidden 的本地化字符串。
        /// </summary>
        public static string 禁止收款 {
            get {
                return ResourceManager.GetString("禁止收款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network error, please try again. 的本地化字符串。
        /// </summary>
        public static string 网络异常_请重新尝试 {
            get {
                return ResourceManager.GetString("网络异常_请重新尝试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order not exist. 的本地化字符串。
        /// </summary>
        public static string 订单不存在 {
            get {
                return ResourceManager.GetString("订单不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order can not be refunded currently 的本地化字符串。
        /// </summary>
        public static string 订单状态异常 {
            get {
                return ResourceManager.GetString("订单状态异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order can not be refuned for more than three days 的本地化字符串。
        /// </summary>
        public static string 订单超过三天不能退款 {
            get {
                return ResourceManager.GetString("订单超过三天不能退款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid invitation code, please enter again 的本地化字符串。
        /// </summary>
        public static string 邀请码不存在 {
            get {
                return ResourceManager.GetString("邀请码不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please finish LV1 certification first before using this function 的本地化字符串。
        /// </summary>
        public static string 需要Lv1认证才能使用相关功能 {
            get {
                return ResourceManager.GetString("需要Lv1认证才能使用相关功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired verification code. 的本地化字符串。
        /// </summary>
        public static string 验证码已过期 {
            get {
                return ResourceManager.GetString("验证码已过期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong verification code. 的本地化字符串。
        /// </summary>
        public static string 验证码有误 {
            get {
                return ResourceManager.GetString("验证码有误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【FiiiPOS】Email verification code 的本地化字符串。
        /// </summary>
        public static string 验证码邮箱标题 {
            get {
                return ResourceManager.GetString("验证码邮箱标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【FiiiPOS】Email verification code：{0}, please do not use it if you are not the intended recipient, valid within {1} minutes. 的本地化字符串。
        /// </summary>
        public static string 验证码邮箱模版 {
            get {
                return ResourceManager.GetString("验证码邮箱模版", resourceCulture);
            }
        }
    }
}
