//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPos.MessageWorkerService.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPos.MessageWorkerService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Refund appeal accepted, check details 的本地化字符串。
        /// </summary>
        public static string BackOfficeRefundOrderSubTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund appeal-{0} 的本地化字符串。
        /// </summary>
        public static string BackOfficeRefundOrderTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have got one payment message, check details 的本地化字符串。
        /// </summary>
        public static string ConsumeSubTitle {
            get {
                return ResourceManager.GetString("ConsumeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense-{0} 的本地化字符串。
        /// </summary>
        public static string ConsumeTitle {
            get {
                return ResourceManager.GetString("ConsumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} deposited failed, check details 的本地化字符串。
        /// </summary>
        public static string DepositCancelSubTitle {
            get {
                return ResourceManager.GetString("DepositCancelSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit-{0} 的本地化字符串。
        /// </summary>
        public static string DepositCancelTitle {
            get {
                return ResourceManager.GetString("DepositCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit of {0} 的本地化字符串。
        /// </summary>
        public static string DepositEmailTitle {
            get {
                return ResourceManager.GetString("DepositEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one deposit completed, check details 的本地化字符串。
        /// </summary>
        public static string DepositSubTitle {
            get {
                return ResourceManager.GetString("DepositSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposited-{0} 的本地化字符串。
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Failed 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Passed 的本地化字符串。
        /// </summary>
        public static string KYC_LV1_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Residential proof was verified failed, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Failed 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Residential proof has been approved, check details 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Passed 的本地化字符串。
        /// </summary>
        public static string KYC_LV2_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity Verify Passed 的本地化字符串。
        /// </summary>
        public static string Merchant_KYC_LV1_DefaultBody {
            get {
                return ResourceManager.GetString("Merchant_KYC_LV1_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license Verify Passed 的本地化字符串。
        /// </summary>
        public static string Merchant_KYC_LV2_DefaultBody {
            get {
                return ResourceManager.GetString("Merchant_KYC_LV2_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Failed 的本地化字符串。
        /// </summary>
        public static string MerchantLv1Reject {
            get {
                return ResourceManager.GetString("MerchantLv1Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv1RejectSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv1RejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Verify Passed 的本地化字符串。
        /// </summary>
        public static string MerchantLv1Verified {
            get {
                return ResourceManager.GetString("MerchantLv1Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv1 Identity verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv1VerifiedSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv1VerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Failed 的本地化字符串。
        /// </summary>
        public static string MerchantLv2Reject {
            get {
                return ResourceManager.GetString("MerchantLv2Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license was verified failed, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv2RejectSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv2RejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Verify Passed 的本地化字符串。
        /// </summary>
        public static string MerchantLv2Verified {
            get {
                return ResourceManager.GetString("MerchantLv2Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv2 Business license has been approved, check details 的本地化字符串。
        /// </summary>
        public static string MerchantLv2VerifiedSubTitle {
            get {
                return ResourceManager.GetString("MerchantLv2VerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have got one payment message, check details 的本地化字符串。
        /// </summary>
        public static string ReceiptSubTitle {
            get {
                return ResourceManager.GetString("ReceiptSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received payment-{0} 的本地化字符串。
        /// </summary>
        public static string ReceiptTitle {
            get {
                return ResourceManager.GetString("ReceiptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one order was refund, check details 的本地化字符串。
        /// </summary>
        public static string RefundSubTitle {
            get {
                return ResourceManager.GetString("RefundSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund-{0} 的本地化字符串。
        /// </summary>
        public static string RefundTitle {
            get {
                return ResourceManager.GetString("RefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Management Verify Failed 的本地化字符串。
        /// </summary>
        public static string StoreReject {
            get {
                return ResourceManager.GetString("StoreReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Management verification was failed, check details 的本地化字符串。
        /// </summary>
        public static string StoreRejectSubTitle {
            get {
                return ResourceManager.GetString("StoreRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Management Verify Passed 的本地化字符串。
        /// </summary>
        public static string StoreVerified {
            get {
                return ResourceManager.GetString("StoreVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Management verification has been approved, check details 的本地化字符串。
        /// </summary>
        public static string StoreVerifiedSubTitle {
            get {
                return ResourceManager.GetString("StoreVerifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have received one transfer from FiiiExchange, check details 的本地化字符串。
        /// </summary>
        public static string TransferFromFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(in)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferFromFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have received one transfer from {0}, check details 的本地化字符串。
        /// </summary>
        public static string TransferIntoSubTitle {
            get {
                return ResourceManager.GetString("TransferIntoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(in)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferIntoTitle {
            get {
                return ResourceManager.GetString("TransferIntoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one transfer completed, check details 的本地化字符串。
        /// </summary>
        public static string TransferOutSubTitle {
            get {
                return ResourceManager.GetString("TransferOutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(out)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferOutTitle {
            get {
                return ResourceManager.GetString("TransferOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one transfer to FiiiExchange completed, check details 的本地化字符串。
        /// </summary>
        public static string TransferToFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer(out)-{0} 的本地化字符串。
        /// </summary>
        public static string TransferToFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal was failed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalRejectTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have one withdrawal completed, check details 的本地化字符串。
        /// </summary>
        public static string WithdrawalSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdraw-{0} 的本地化字符串。
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonus-FIII 的本地化字符串。
        /// </summary>
        public static string 奖励FIII {
            get {
                return ResourceManager.GetString("奖励FIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonus of FiiiCoin has been arrived your account, check details 的本地化字符串。
        /// </summary>
        public static string 奖励子标题 {
            get {
                return ResourceManager.GetString("奖励子标题", resourceCulture);
            }
        }
    }
}
