//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Framework.Component.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Framework.Component.Properties.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error， please login again.
        /// </summary>
        public static string EMAccessTokenExpire {
            get {
                return ResourceManager.GetString("EMAccessTokenExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or password error, {0} attempts left.
        /// </summary>
        public static string EMAccountPasswordError {
            get {
                return ResourceManager.GetString("EMAccountPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【FiiiPay】Email verification code：{0}, please do not use it if you are not the intended recipient, valid within {1} minutes.
        /// </summary>
        public static string EmailVerfiyMessage {
            get {
                return ResourceManager.GetString("EmailVerfiyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the generation of new google  authentication code.
        /// </summary>
        public static string EMGoogleCodeBeUsed {
            get {
                return ResourceManager.GetString("EMGoogleCodeBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google authentication code error, {0} attempts left.
        /// </summary>
        public static string EMGoogleCodeError {
            get {
                return ResourceManager.GetString("EMGoogleCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ID number, {0} attempt left.
        /// </summary>
        public static string EMIdentityNoError {
            get {
                return ResourceManager.GetString("EMIdentityNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal address.
        /// </summary>
        public static string EMInvalidAddress {
            get {
                return ResourceManager.GetString("EMInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tag.
        /// </summary>
        public static string EMInvalidTag {
            get {
                return ResourceManager.GetString("EMInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login attempts reach limit, please try again {0} minutes later .
        /// </summary>
        public static string EMLoginSMSCodeTry5Times {
            get {
                return ResourceManager.GetString("EMLoginSMSCodeTry5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the address or input a valid tag.
        /// </summary>
        public static string EMNeedInputTag {
            get {
                return ResourceManager.GetString("EMNeedInputTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password error, {0} attempts left.
        /// </summary>
        public static string EMPasswordError {
            get {
                return ResourceManager.GetString("EMPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification attempts reach limit, please try again {0} minutes later.
        /// </summary>
        public static string EMPasswordError5Times {
            get {
                return ResourceManager.GetString("EMPasswordError5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login attempts reach limit, please try again {0} minutes later or retrieve password.
        /// </summary>
        public static string EMPasswordTry5Times {
            get {
                return ResourceManager.GetString("EMPasswordTry5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN error, {0} attempts left.
        /// </summary>
        public static string EMPINInputError {
            get {
                return ResourceManager.GetString("EMPINInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is locked and will be unlocked {0} minutes later..
        /// </summary>
        public static string EMPINInputLimit {
            get {
                return ResourceManager.GetString("EMPINInputLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification attempts reach limit, please try again {0} minutes later.
        /// </summary>
        public static string EMRegisterVerifyLimit5Times {
            get {
                return ResourceManager.GetString("EMRegisterVerifyLimit5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS code error, {0} attempts left.
        /// </summary>
        public static string EMSMSCodeError {
            get {
                return ResourceManager.GetString("EMSMSCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification expired.
        /// </summary>
        public static string EMSMSCodeExpire {
            get {
                return ResourceManager.GetString("EMSMSCodeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify failed,{0} attempts left.
        /// </summary>
        public static string EMVerifyFaild {
            get {
                return ResourceManager.GetString("EMVerifyFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification attempts reach limit, please try again {0} minutes later.
        /// </summary>
        public static string EMVerifyFaildMoreTimes {
            get {
                return ResourceManager.GetString("EMVerifyFaildMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification attempts reach limit, please try again {0} minutes later.
        /// </summary>
        public static string EMVerifyLimit5Times {
            get {
                return ResourceManager.GetString("EMVerifyLimit5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google authentication code error, please re-enter.
        /// </summary>
        public static string GACodeError {
            get {
                return ResourceManager.GetString("GACodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QR code, please scan again.
        /// </summary>
        public static string InvalidQRCode {
            get {
                return ResourceManager.GetString("InvalidQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification message error, {0} attempt left.
        /// </summary>
        public static string SecurityValidateError {
            get {
                return ResourceManager.GetString("SecurityValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code:{0}, valid for {1} mins only --FiiiPay.
        /// </summary>
        public static string SMS_Template_FiiiPay {
            get {
                return ResourceManager.GetString("SMS_Template_FiiiPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code:{0}, valid for {1} mins only --FiiiPOS.
        /// </summary>
        public static string SMS_Template_POS {
            get {
                return ResourceManager.GetString("SMS_Template_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification times exceed limit, please try again tomorrow.
        /// </summary>
        public static string SMSLimit {
            get {
                return ResourceManager.GetString("SMSLimit", resourceCulture);
            }
        }
    }
}
