CREATE TABLE [dbo].[UserProfiles] (
    [UserAccountId]      UNIQUEIDENTIFIER NOT NULL,
    [LastName]           NVARCHAR (100)   NOT NULL,
    [FirstName]          NVARCHAR (100)   NULL,
    [L1VerifyStatus]     TINYINT          NULL,
    [L2VerifyStatus]     TINYINT          NULL,
    [IdentityDocNo]      NVARCHAR (50)    NULL,
    [IdentityDocType]    TINYINT          NULL,
    [IdentityExpiryDate] DATETIME         NULL,
    [DateOfBirth]        DATETIME         NULL,
    [Address1]           NVARCHAR (200)   NULL,
    [Address2]           NVARCHAR (200)   NULL,
    [City]               NVARCHAR (32)    NULL,
    [State]              NVARCHAR (32)    NULL,
    [Postcode]           NVARCHAR(50)     NULL,
    [Country]            INT              NOT NULL,
    [Gender]             TINYINT          NULL,
    [FrontIdentityImage] UNIQUEIDENTIFIER NULL,
    [ResidentImage]      UNIQUEIDENTIFIER NULL,
    [BackIdentityImage]  UNIQUEIDENTIFIER NULL,
    [HandHoldWithCard]   UNIQUEIDENTIFIER NULL,
    [L1SubmissionDate]   DATETIME         NULL,
    [L2SubmissionDate]   DATETIME         NULL,
    [Remark]             NVARCHAR (50)    NULL,
    [AccountStatus]      BIT              NULL,
    [Cellphone]          VARCHAR (50)     NULL,
    [L1Remark]           NVARCHAR (500)   NULL,
    [L2Remark]           NVARCHAR (500)   NULL, 
    CONSTRAINT [PK_UserProfiles] PRIMARY KEY ([UserAccountId])
);

