//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Business.Properties.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account {0} already exist. 的本地化字符串。
        /// </summary>
        public static string AccountAlreadyExist {
            get {
                return ResourceManager.GetString("AccountAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System has disabled the account, please contact customer service 的本地化字符串。
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been verified or under review 的本地化字符串。
        /// </summary>
        public static string AccountHasBeenVerification {
            get {
                return ResourceManager.GetString("AccountHasBeenVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account is locked. 的本地化字符串。
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account does not exist 的本地化字符串。
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account not found. 的本地化字符串。
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user does not match. 的本地化字符串。
        /// </summary>
        public static string AccountNotMatch {
            get {
                return ResourceManager.GetString("AccountNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add address successfully 的本地化字符串。
        /// </summary>
        public static string AddAddressSuccess {
            get {
                return ResourceManager.GetString("AddAddressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address not exist 的本地化字符串。
        /// </summary>
        public static string AddressNotExist {
            get {
                return ResourceManager.GetString("AddressNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount need to be greater than 0 的本地化字符串。
        /// </summary>
        public static string AmountGreater {
            get {
                return ResourceManager.GetString("AmountGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account has been logged in from another device. 的本地化字符串。
        /// </summary>
        public static string AnotherDeviceLogin {
            get {
                return ResourceManager.GetString("AnotherDeviceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrival amount cannot be zero or minus 的本地化字符串。
        /// </summary>
        public static string ArrivalAmountError {
            get {
                return ResourceManager.GetString("ArrivalAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change success 的本地化字符串。
        /// </summary>
        public static string ChangSuccess {
            get {
                return ResourceManager.GetString("ChangSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country is required. 的本地化字符串。
        /// </summary>
        public static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country not found. 的本地化字符串。
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System is under maintenance in your area 的本地化字符串。
        /// </summary>
        public static string CountryRequestForbbiden {
            get {
                return ResourceManager.GetString("CountryRequestForbbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cryptocurrency cannot be used currently, please contact customer service if any question 的本地化字符串。
        /// </summary>
        public static string CurrencyForbidden {
            get {
                return ResourceManager.GetString("CurrencyForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email already set 的本地化字符串。
        /// </summary>
        public static string EmailAlredaySet {
            get {
                return ResourceManager.GetString("EmailAlredaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email account already exit on FiiiPay, please try with new one 的本地化字符串。
        /// </summary>
        public static string EmailHasBind {
            get {
                return ResourceManager.GetString("EmailHasBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email verification code error 的本地化字符串。
        /// </summary>
        public static string EmailVerificationError {
            get {
                return ResourceManager.GetString("EmailVerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error crypto code 的本地化字符串。
        /// </summary>
        public static string ErrorCryptoCode {
            get {
                return ResourceManager.GetString("ErrorCryptoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FiiiEx account not found 的本地化字符串。
        /// </summary>
        public static string FiiiExAccountNotExist {
            get {
                return ResourceManager.GetString("FiiiExAccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FiiiPay user cannot withdraw to FiiiPOS, please use Scan, Payment Code to finish payment and transaction. 的本地化字符串。
        /// </summary>
        public static string FiiiPayCantWithdrawToFiiiPOS {
            get {
                return ResourceManager.GetString("FiiiPayCantWithdrawToFiiiPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excessive use of this ID number 的本地化字符串。
        /// </summary>
        public static string IdentityUsedOverLimit {
            get {
                return ResourceManager.GetString("IdentityUsedOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect original email addreess 的本地化字符串。
        /// </summary>
        public static string IncorrectOriginalEmailAddress {
            get {
                return ResourceManager.GetString("IncorrectOriginalEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect original password 的本地化字符串。
        /// </summary>
        public static string IncorrectOriginalPassword {
            get {
                return ResourceManager.GetString("IncorrectOriginalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient balance 的本地化字符串。
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual number is not registrable 的本地化字符串。
        /// </summary>
        public static string InvalidCellphone {
            get {
                return ResourceManager.GetString("InvalidCellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid data format. 的本地化字符串。
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid format. 的本地化字符串。
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid invitation code, please enter again 的本地化字符串。
        /// </summary>
        public static string InvalidInvitation {
            get {
                return ResourceManager.GetString("InvalidInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid request parameters 的本地化字符串。
        /// </summary>
        public static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid QR code, please scan again 的本地化字符串。
        /// </summary>
        public static string InvalidQRCode {
            get {
                return ResourceManager.GetString("InvalidQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid withdrawal address 的本地化字符串。
        /// </summary>
        public static string InvalidWithdrawalAddress {
            get {
                return ResourceManager.GetString("InvalidWithdrawalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input a invite code which is not your own 的本地化字符串。
        /// </summary>
        public static string InviteCodeCanotInputSelf {
            get {
                return ResourceManager.GetString("InviteCodeCanotInputSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 50 letters limit 的本地化字符串。
        /// </summary>
        public static string LenLimit {
            get {
                return ResourceManager.GetString("LenLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1000 letters limit 的本地化字符串。
        /// </summary>
        public static string LenLimit1000 {
            get {
                return ResourceManager.GetString("LenLimit1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 300 letters limit 的本地化字符串。
        /// </summary>
        public static string LenLimit300 {
            get {
                return ResourceManager.GetString("LenLimit300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account exception, the transaction has been canceled 的本地化字符串。
        /// </summary>
        public static string MerchantAccountDisabled {
            get {
                return ResourceManager.GetString("MerchantAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant account exception, does not support trading now  的本地化字符串。
        /// </summary>
        public static string MerchantExceptionTransClose {
            get {
                return ResourceManager.GetString("MerchantExceptionTransClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction function error, payment cancel 的本地化字符串。
        /// </summary>
        public static string MerchantExpenseNotAllowed {
            get {
                return ResourceManager.GetString("MerchantExpenseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop&apos;s FiiiPay account is abnormal, payment is cancelled 的本地化字符串。
        /// </summary>
        public static string MerchantFiiipayAbnormal {
            get {
                return ResourceManager.GetString("MerchantFiiipayAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The shop has been removed 的本地化字符串。
        /// </summary>
        public static string MerchantNotPublic {
            get {
                return ResourceManager.GetString("MerchantNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant does not support this cryptocurrency  的本地化字符串。
        /// </summary>
        public static string MerchantNotSupperCrypto {
            get {
                return ResourceManager.GetString("MerchantNotSupperCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop&apos;s FiiiPay function is abnormal, payment is cancelled 的本地化字符串。
        /// </summary>
        public static string MerchantReceiveNotAllowed {
            get {
                return ResourceManager.GetString("MerchantReceiveNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot less than the minimal withdrawal amount 的本地化字符串。
        /// </summary>
        public static string MinWidrawalError {
            get {
                return ResourceManager.GetString("MinWidrawalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account already exist, please try with a new phone number 的本地化字符串。
        /// </summary>
        public static string MobilePhoneHasReg {
            get {
                return ResourceManager.GetString("MobilePhoneHasReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdrawal amount reach the limit of this month 的本地化字符串。
        /// </summary>
        public static string MonthWithdrawalLimit {
            get {
                return ResourceManager.GetString("MonthWithdrawalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network error, please try again. 的本地化字符串。
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New and old email address can not be the same 的本地化字符串。
        /// </summary>
        public static string NewMailOldSame {
            get {
                return ResourceManager.GetString("NewMailOldSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New and old password can not be the same 的本地化字符串。
        /// </summary>
        public static string NewPasswordHasUse {
            get {
                return ResourceManager.GetString("NewPasswordHasUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New PIN should be different from old PIN 的本地化字符串。
        /// </summary>
        public static string NewPINOldPINDifferent {
            get {
                return ResourceManager.GetString("NewPINOldPINDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account have not fill in email address 的本地化字符串。
        /// </summary>
        public static string NotBindMail {
            get {
                return ResourceManager.GetString("NotBindMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not verify Google authenticator 的本地化字符串。
        /// </summary>
        public static string NotVerifiyGA {
            get {
                return ResourceManager.GetString("NotVerifiyGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order is paied or refunded, please do not pay again 的本地化字符串。
        /// </summary>
        public static string OrderComplated {
            get {
                return ResourceManager.GetString("OrderComplated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order has expired. 的本地化字符串。
        /// </summary>
        public static string OrderHasExpired {
            get {
                return ResourceManager.GetString("OrderHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order not found. 的本地化字符串。
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order to be refund. 的本地化字符串。
        /// </summary>
        public static string OrderRefund {
            get {
                return ResourceManager.GetString("OrderRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is required. 的本地化字符串。
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment forbidden 的本地化字符串。
        /// </summary>
        public static string PaymentForbidden {
            get {
                return ResourceManager.GetString("PaymentForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to pay to your own account 的本地化字符串。
        /// </summary>
        public static string PaytoSelf {
            get {
                return ResourceManager.GetString("PaytoSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone number is required. 的本地化字符串。
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN error, {0} time left to enter 的本地化字符串。
        /// </summary>
        public static string PINError {
            get {
                return ResourceManager.GetString("PINError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN was set, please do not set again 的本地化字符串。
        /// </summary>
        public static string PINHasSet {
            get {
                return ResourceManager.GetString("PINHasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN Invalid format. 的本地化字符串。
        /// </summary>
        public static string PINInvalidFormat {
            get {
                return ResourceManager.GetString("PINInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN enter error for 5 times, frozen temporary, please try again  in 30 minutes 的本地化字符串。
        /// </summary>
        public static string PINMaxError {
            get {
                return ResourceManager.GetString("PINMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This red packet is expired 的本地化字符串。
        /// </summary>
        public static string RedPocket_Expired {
            get {
                return ResourceManager.GetString("RedPocket_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All red packets have been claimed 的本地化字符串。
        /// </summary>
        public static string RedPocket_HasComplet {
            get {
                return ResourceManager.GetString("RedPocket_HasComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have already claimed this red packet 的本地化字符串。
        /// </summary>
        public static string RedPocket_HasReceive {
            get {
                return ResourceManager.GetString("RedPocket_HasReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single red packet amount shall not exceed {0} {1} 的本地化字符串。
        /// </summary>
        public static string RedPocket_MaxAmount {
            get {
                return ResourceManager.GetString("RedPocket_MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum quantity of red packet is 100 的本地化字符串。
        /// </summary>
        public static string RedPocket_MaxCount {
            get {
                return ResourceManager.GetString("RedPocket_MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have entered wrong password for {0} times, please retry after {1} minutes. 的本地化字符串。
        /// </summary>
        public static string RedPocket_MaxError {
            get {
                return ResourceManager.GetString("RedPocket_MaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wishes shall not exceed 46 words 的本地化字符串。
        /// </summary>
        public static string RedPocket_MaxMessage {
            get {
                return ResourceManager.GetString("RedPocket_MaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum amount is {0} {1} 的本地化字符串。
        /// </summary>
        public static string RedPocket_MinAmount {
            get {
                return ResourceManager.GetString("RedPocket_MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong password for {0} time(s), if {1} more failure(s) occured, you are forbidden to enter password for 6 hours 的本地化字符串。
        /// </summary>
        public static string RedPocket_PassCodeError {
            get {
                return ResourceManager.GetString("RedPocket_PassCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have entered wrong password for 10 times, please retry after {0}. 的本地化字符串。
        /// </summary>
        public static string RedPocket_PassCodeErrorMaxCount {
            get {
                return ResourceManager.GetString("RedPocket_PassCodeErrorMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, your red packet password has expired. 的本地化字符串。
        /// </summary>
        public static string RedPocket_ReceiveExpired {
            get {
                return ResourceManager.GetString("RedPocket_ReceiveExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration success. 的本地化字符串。
        /// </summary>
        public static string RegSuccess {
            get {
                return ResourceManager.GetString("RegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification message error, {0} attempt left 的本地化字符串。
        /// </summary>
        public static string SecurityValidateError {
            get {
                return ResourceManager.GetString("SecurityValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification time reach limit, please try again in {0} minutes 的本地化字符串。
        /// </summary>
        public static string SecurityWrongTooManyTimes {
            get {
                return ResourceManager.GetString("SecurityWrongTooManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification times exceed limit, please try again tomorrow 的本地化字符串。
        /// </summary>
        public static string SMSLimit {
            get {
                return ResourceManager.GetString("SMSLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS verification code error 的本地化字符串。
        /// </summary>
        public static string SMSVerifCodeError {
            get {
                return ResourceManager.GetString("SMSVerifCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System error. 的本地化字符串。
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payee&apos;s FiiiPay account is abnormal, unable to transfer. Please contact our customer service. 的本地化字符串。
        /// </summary>
        public static string ToAccountTransferForbidden {
            get {
                return ResourceManager.GetString("ToAccountTransferForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reach the withdrawal limit today 的本地化字符串。
        /// </summary>
        public static string TodayWidrawalLimit {
            get {
                return ResourceManager.GetString("TodayWidrawalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single transaction amount shall not exceed {0} {1} 的本地化字符串。
        /// </summary>
        public static string TransferAmountOverflow {
            get {
                return ResourceManager.GetString("TransferAmountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lower than minimal transfer amount 的本地化字符串。
        /// </summary>
        public static string TransferAmountTooSmall {
            get {
                return ResourceManager.GetString("TransferAmountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter amount exceed balance 的本地化字符串。
        /// </summary>
        public static string TransferBalanceLow {
            get {
                return ResourceManager.GetString("TransferBalanceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account exception, this function cannot be used currently, please contact customer service 的本地化字符串。
        /// </summary>
        public static string TransferForbidden {
            get {
                return ResourceManager.GetString("TransferForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot transfer to yourself 的本地化字符串。
        /// </summary>
        public static string TransferToSelf {
            get {
                return ResourceManager.GetString("TransferToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload failed. 的本地化字符串。
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code error, please try it again. 的本地化字符串。
        /// </summary>
        public static string VerificationCodeError {
            get {
                return ResourceManager.GetString("VerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code is invalid or has expired. 的本地化字符串。
        /// </summary>
        public static string VerificationCodeExpired {
            get {
                return ResourceManager.GetString("VerificationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code is required. 的本地化字符串。
        /// </summary>
        public static string VerificationCodeRequired {
            get {
                return ResourceManager.GetString("VerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification information error 的本地化字符串。
        /// </summary>
        public static string VerificationInfoError {
            get {
                return ResourceManager.GetString("VerificationInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification information expired 的本地化字符串。
        /// </summary>
        public static string VerificationInfoExpired {
            get {
                return ResourceManager.GetString("VerificationInfoExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code request reached the limit 的本地化字符串。
        /// </summary>
        public static string VerificationMaxLimit {
            get {
                return ResourceManager.GetString("VerificationMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account exception, please contact customer service 的本地化字符串。
        /// </summary>
        public static string WithdrawalDisabled {
            get {
                return ResourceManager.GetString("WithdrawalDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order exception, rejected by system, please contact customer service 的本地化字符串。
        /// </summary>
        public static string WithdrawalErrorRemark {
            get {
                return ResourceManager.GetString("WithdrawalErrorRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withdrawal address cannot be your own address 的本地化字符串。
        /// </summary>
        public static string WithdrawalToSelfError {
            get {
                return ResourceManager.GetString("WithdrawalToSelfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong password enterred. 的本地化字符串。
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password error,account is disabled,try again in {0} minutes 的本地化字符串。
        /// </summary>
        public static string WrongPassword_Lock {
            get {
                return ResourceManager.GetString("WrongPassword_Lock", resourceCulture);
            }
        }
    }
}
