//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer refund appeal accpeted, platform will return the order amount.
        /// </summary>
        public static string BackOfficeRefundOrderSubTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund appeal-{0}.
        /// </summary>
        public static string BackOfficeRefundOrderTitle {
            get {
                return ResourceManager.GetString("BackOfficeRefundOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Biller already exists.
        /// </summary>
        public static string BillerAddressExisted {
            get {
                return ResourceManager.GetString("BillerAddressExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have got one pay bill message, check details.
        /// </summary>
        public static string BillerCompleteSubTitle {
            get {
                return ResourceManager.GetString("BillerCompleteSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill.
        /// </summary>
        public static string BillerDetailType {
            get {
                return ResourceManager.GetString("BillerDetailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange rate may be updated from time to time. The actual amount has changed, please remake the payment..
        /// </summary>
        public static string BillerExchangeRateError {
            get {
                return ResourceManager.GetString("BillerExchangeRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have failed to make one pay bill, check details.
        /// </summary>
        public static string BillerFailSubTitle {
            get {
                return ResourceManager.GetString("BillerFailSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill Failed-{0}.
        /// </summary>
        public static string BillerFailTitle {
            get {
                return ResourceManager.GetString("BillerFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not available now, please contact our customer service..
        /// </summary>
        public static string BillerForbidden {
            get {
                return ResourceManager.GetString("BillerForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill Failed.
        /// </summary>
        public static string BillerMessageFailTitle {
            get {
                return ResourceManager.GetString("BillerMessageFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string BillerOrderComplete {
            get {
                return ResourceManager.GetString("BillerOrderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed and refunded.
        /// </summary>
        public static string BillerOrderFail {
            get {
                return ResourceManager.GetString("BillerOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string BillerOrderPending {
            get {
                return ResourceManager.GetString("BillerOrderPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only up to 500 Billers are allowed..
        /// </summary>
        public static string BillerOverAddressMaxCount {
            get {
                return ResourceManager.GetString("BillerOverAddressMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching the daily payment limit, please try it again tomorrow.
        /// </summary>
        public static string BillerOverDayMaxAmount {
            get {
                return ResourceManager.GetString("BillerOverDayMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single payment cannot exceed {0}.
        /// </summary>
        public static string BillerOverMaxAmount {
            get {
                return ResourceManager.GetString("BillerOverMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaching the monthly payment limit, please try it again next month..
        /// </summary>
        public static string BillerOverMonthMaxAmount {
            get {
                return ResourceManager.GetString("BillerOverMonthMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Bill-{0}.
        /// </summary>
        public static string BillerTitle {
            get {
                return ResourceManager.GetString("BillerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment.
        /// </summary>
        public static string BillTypeNetOrder {
            get {
                return ResourceManager.GetString("BillTypeNetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string BonusComeFrom {
            get {
                return ResourceManager.GetString("BonusComeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reward from Invitation activity.
        /// </summary>
        public static string BonusDescription {
            get {
                return ResourceManager.GetString("BonusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus-FIII.
        /// </summary>
        public static string BonusFIII {
            get {
                return ResourceManager.GetString("BonusFIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward-Earning.
        /// </summary>
        public static string BonusIncome {
            get {
                return ResourceManager.GetString("BonusIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus of FiiiCoin has been arrived your account, check details.
        /// </summary>
        public static string BonusSubTitle {
            get {
                return ResourceManager.GetString("BonusSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have got one payment message, check details.
        /// </summary>
        public static string ConsumeSubTitle {
            get {
                return ResourceManager.GetString("ConsumeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense-{0}.
        /// </summary>
        public static string ConsumeTitle {
            get {
                return ResourceManager.GetString("ConsumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string DepositCancelled {
            get {
                return ResourceManager.GetString("DepositCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deposited failed, check details.
        /// </summary>
        public static string DepositCancelSubTitle {
            get {
                return ResourceManager.GetString("DepositCancelSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit-{0}.
        /// </summary>
        public static string DepositCancelTitle {
            get {
                return ResourceManager.GetString("DepositCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string DepositConfirmed {
            get {
                return ResourceManager.GetString("DepositConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} has been deposited to your account.
        /// </summary>
        public static string DepositEmailContent {
            get {
                return ResourceManager.GetString("DepositEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit of {0}.
        /// </summary>
        public static string DepositEmailTitle {
            get {
                return ResourceManager.GetString("DepositEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DepositPending {
            get {
                return ResourceManager.GetString("DepositPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one deposit completed, check details.
        /// </summary>
        public static string DepositSubTitle {
            get {
                return ResourceManager.GetString("DepositSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposited-{0}.
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【FiiiPay】Email verification code：{0}, please do not use it if you are not the intended recipient, valid within {1} minutes.
        /// </summary>
        public static string Email_Template {
            get {
                return ResourceManager.GetString("Email_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please finish LV1 certification first before using this function.
        /// </summary>
        public static string EMNeedLV1Verfied {
            get {
                return ResourceManager.GetString("EMNeedLV1Verfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The withdrawal and deposit function is not ready currently, we will announce officially once ready.
        /// </summary>
        public static string EMNotSupportWithdrawl {
            get {
                return ResourceManager.GetString("EMNotSupportWithdrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate address.
        /// </summary>
        public static string FailedGenerateAddress {
            get {
                return ResourceManager.GetString("FailedGenerateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has passed the review，check details.
        /// </summary>
        public static string FiiipayMerchantCertifiedSubTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantCertifiedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Review - Pass.
        /// </summary>
        public static string FiiipayMerchantCertifiedTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantCertifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your application has failed to pass the review\n\nSorry, your application has failed to pass the review.\nReason:{0} 的本地化字符串。
        /// </summary>
        public static string FiiipayMerchantDisapprovalDetail {
            get {
                return ResourceManager.GetString("FiiipayMerchantDisapprovalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has failed to pass the review , check details.
        /// </summary>
        public static string FiiipayMerchantDisapprovalSubTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantDisapprovalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Review - Fail.
        /// </summary>
        public static string FiiipayMerchantDisapprovalTitle {
            get {
                return ResourceManager.GetString("FiiipayMerchantDisapprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has passed the review\n\nCongratulation! Your application has passed the review. The shop information submitted by you will be displayed on your shop.
        /// </summary>
        public static string FiiipayMerchantVerifyDetail {
            get {
                return ResourceManager.GetString("FiiipayMerchantVerifyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This FiiiPOS has accepted your invitation, the merchant name is {0}.
        /// </summary>
        public static string FiiiposInviteSuccessContent {
            get {
                return ResourceManager.GetString("FiiiposInviteSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward-Invite FiiiPOS to Register.
        /// </summary>
        public static string FiiiposInviteSuccessTitle {
            get {
                return ResourceManager.GetString("FiiiposInviteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiiiPOS from your account, the merchant name is {0}.
        /// </summary>
        public static string FiiiposUnbindContent {
            get {
                return ResourceManager.GetString("FiiiposUnbindContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward-Unbind FiiiPOS from Your Account.
        /// </summary>
        public static string FiiiposUnbindTitle {
            get {
                return ResourceManager.GetString("FiiiposUnbindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your refund request has finished, check details.
        /// </summary>
        public static string GatewayOrderPaymentRefundSubTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentRefundSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund-{0}.
        /// </summary>
        public static string GatewayOrderPaymentRefundTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentRefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an online payment order, check details.
        /// </summary>
        public static string GatewayOrderPaymentSubTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment-{0}.
        /// </summary>
        public static string GatewayOrderPaymentTitle {
            get {
                return ResourceManager.GetString("GatewayOrderPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This FiiiPOS has accepted your invitation, the merchant name is {0}.
        /// </summary>
        public static string InviteFiiiposSuccessSubTitle {
            get {
                return ResourceManager.GetString("InviteFiiiposSuccessSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward-Invite FiiiPOS to Register.
        /// </summary>
        public static string InviteFiiiposSuccessTitle {
            get {
                return ResourceManager.GetString("InviteFiiiposSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 Identity verification was failed, check details.
        /// </summary>
        public static string KYC_LV1_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 Verify Failed.
        /// </summary>
        public static string KYC_LV1_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 Identity verification has been approved, check details.
        /// </summary>
        public static string KYC_LV1_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 Verify Passed.
        /// </summary>
        public static string KYC_LV1_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV1_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv2 Residential proof was verified failed, check details.
        /// </summary>
        public static string KYC_LV2_REJECTSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv2 Verify Failed.
        /// </summary>
        public static string KYC_LV2_REJECTTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_REJECTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv2 Residential proof has been approved, check details.
        /// </summary>
        public static string KYC_LV2_VERIFIEDSubTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv2 Verify Passed.
        /// </summary>
        public static string KYC_LV2_VERIFIEDTitle {
            get {
                return ResourceManager.GetString("KYC_LV2_VERIFIEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 verified，Lv2 to be verified.
        /// </summary>
        public static string Lv1_Lv2 {
            get {
                return ResourceManager.GetString("Lv1_Lv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html,
        ///            body {
        ///                box-sizing: border-box;
        ///                margin: 0;
        ///                padding: 0;
        ///                min-width: 320px;
        ///                font-family: &quot;PingFang SC&quot;;
        ///                font-size: 100%;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewsTemplate {
            get {
                return ResourceManager.GetString("NewsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string OrderClosed {
            get {
                return ResourceManager.GetString("OrderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string OrderCompleted {
            get {
                return ResourceManager.GetString("OrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string OrderPending {
            get {
                return ResourceManager.GetString("OrderPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        public static string OrderRefunded {
            get {
                return ResourceManager.GetString("OrderRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify {0} again.
        /// </summary>
        public static string Recertification {
            get {
                return ResourceManager.GetString("Recertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress,Completed,Partial Refund,Full Refund.
        /// </summary>
        public static string RedPocketStatus {
            get {
                return ResourceManager.GetString("RedPocketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund completed, check details.
        /// </summary>
        public static string RefundSubTitle {
            get {
                return ResourceManager.GetString("RefundSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund-{0}.
        /// </summary>
        public static string RefundTitle {
            get {
                return ResourceManager.GetString("RefundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiiiPOS from your account, the merchant name is {0}.
        /// </summary>
        public static string RewardUnbindFiiiposSubTitle {
            get {
                return ResourceManager.GetString("RewardUnbindFiiiposSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward-Unbind FiiiPOS from Your Account.
        /// </summary>
        public static string RewardUnbindFiiiposTitle {
            get {
                return ResourceManager.GetString("RewardUnbindFiiiposTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code:{0}, valid for {1} mins only --FiiiPay.
        /// </summary>
        public static string SMS_Template {
            get {
                return ResourceManager.GetString("SMS_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made a payment, see details.
        /// </summary>
        public static string StoreOrderConsumeSubTitle {
            get {
                return ResourceManager.GetString("StoreOrderConsumeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline payment-{0}.
        /// </summary>
        public static string StoreOrderConsumeTitle {
            get {
                return ResourceManager.GetString("StoreOrderConsumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Incomes.
        /// </summary>
        public static string StoreOrderIncome {
            get {
                return ResourceManager.GetString("StoreOrderIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a payment, see detail.
        /// </summary>
        public static string StoreOrderIncomeSubTitle {
            get {
                return ResourceManager.GetString("StoreOrderIncomeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Received-{0}.
        /// </summary>
        public static string StoreOrderIncomeTitle {
            get {
                return ResourceManager.GetString("StoreOrderIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be verified.
        /// </summary>
        public static string ToBeVerification {
            get {
                return ResourceManager.GetString("ToBeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received one transfer from FiiiExchange, check details.
        /// </summary>
        public static string TransferFromFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer(in)-{0}.
        /// </summary>
        public static string TransferFromFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferFromFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer-In.
        /// </summary>
        public static string TransferInto {
            get {
                return ResourceManager.GetString("TransferInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received one transfer from {0}, check details.
        /// </summary>
        public static string TransferIntoSubTitle {
            get {
                return ResourceManager.GetString("TransferIntoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer(in)-{0}.
        /// </summary>
        public static string TransferIntoTitle {
            get {
                return ResourceManager.GetString("TransferIntoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer-Out.
        /// </summary>
        public static string TransferOut {
            get {
                return ResourceManager.GetString("TransferOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one transfer completed, check details.
        /// </summary>
        public static string TransferOutSubTitle {
            get {
                return ResourceManager.GetString("TransferOutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer(out)-{0}.
        /// </summary>
        public static string TransferOutTitle {
            get {
                return ResourceManager.GetString("TransferOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one transfer to FiiiExchange completed, check details.
        /// </summary>
        public static string TransferToFiiiExSubTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer(out)-{0}.
        /// </summary>
        public static string TransferToFiiiExTitle {
            get {
                return ResourceManager.GetString("TransferToFiiiExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under review.
        /// </summary>
        public static string UnderReview {
            get {
                return ResourceManager.GetString("UnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv1 Identity Verify Passed.
        /// </summary>
        public static string User_KYC_LV1_DefaultBody {
            get {
                return ResourceManager.GetString("User_KYC_LV1_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv2 Residential proof Verify Passed.
        /// </summary>
        public static string User_KYC_LV2_DefaultBody {
            get {
                return ResourceManager.GetString("User_KYC_LV2_DefaultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【FiiiPay】Email verification code.
        /// </summary>
        public static string VerificationCodoEmailTitle {
            get {
                return ResourceManager.GetString("VerificationCodoEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify Lv1 in advance.
        /// </summary>
        public static string VerificationLv1First {
            get {
                return ResourceManager.GetString("VerificationLv1First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesfully withdraw {0} of {1}.
        /// </summary>
        public static string WithdrawalEmailContent {
            get {
                return ResourceManager.GetString("WithdrawalEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal of {0}.
        /// </summary>
        public static string WithdrawalEmailTitle {
            get {
                return ResourceManager.GetString("WithdrawalEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have failed to withdraw {0} of {1}, please contact customer service.
        /// </summary>
        public static string WithdrawalRejectEmailContent {
            get {
                return ResourceManager.GetString("WithdrawalRejectEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal of {0}.
        /// </summary>
        public static string WithdrawalRejectEmailTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one withdrawal was failed, check details.
        /// </summary>
        public static string WithdrawalRejectSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw-{0}.
        /// </summary>
        public static string WithdrawalRejectTitle {
            get {
                return ResourceManager.GetString("WithdrawalRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one withdrawal completed, check details.
        /// </summary>
        public static string WithdrawalSubTitle {
            get {
                return ResourceManager.GetString("WithdrawalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw-{0}.
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
    }
}
